project/project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('robots/',include('robots.urls',namespace='robots')),
   
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/robots/urls.py
from django.urls import path

from .import views
from .models import Schedule

app_name='robots'
urlpatterns = [ 

   
  # TEMPORARY
    path('', views.sign_in, name='signin'),
    path('signout', views.sign_out, name='signout'),
    path('callback', views.callback, name='callback'),
    path('calendar', views.calendar, name='calendar'),

    path('home',views.Robot_Listing,name='home'),
    path('<int:id>/',views.Robot_Details,name='robot_details'),
    path('robot_list/',views.Robot_List,name='robot_list'),
    path('location_list/',views.Location_List,name='location_list'),
    path('category_list/',views.Category_List,name='category_list'),
    path('Schedule_Details/',views.Schedule_Details,name='schedule_details'),
    path('schedule_Submit/',views.schedule_Submit,name='schedule_Submit'),
    path('Robot_Search/',views.Robot_Search,name='Robot_Search'),
    path('schedule_list/',views.Schedule_List,name='schedule_list'),
    path('schedule_edit/<Process_ID>/',views.Schedule_edit,name='schedule_edit'),
    path('schedule_update/',views.Schedule_Update,name='schedule_update'),
    path('schedule_delete/<Process_ID>/',views.Schedule_Delete,name='schedule_delete'),
    path('robot_listing_search/',views.Robot_Listing_Search,name='robot_listing_search'),
    path('history_list/',views.History_List,name='history_list'),
    path('history_listing_search/',views.History_Listing_Search,name='history_listing_search'),
    path('history_details/<Process_ID>/',views.History_Details,name='history_details'),
]

project/robots/models.py
from django.db import models
STATUS_CHOICES = [
    ('IOT', 'INTERNET OF THINGS'),
    ('MANUAL', 'MANUAL'),
    ('SWITCH', 'SWICTH CLICK'),
    ('LS', 'LOCAL SCHEDULE'),
    
]


class Category(models.Model):
    Name=models.CharField(max_length=50)
    Description=models.TextField(max_length=500,null=True,blank=True)
    def __str__ (self):
            return self.Name

class Location(models.Model):
    Name=models.CharField(max_length=50)
    Group=models.CharField(max_length=50,null=True,blank=True)
    Description=models.TextField(max_length=500,null=True,blank=True)
    def __str__ (self):
            return self.Name
class Robot( models.Model):
    Name=models.CharField(max_length=50)
    Model=models.CharField(max_length=50) 
    SN=models.CharField(max_length=50) 
    Software=models.CharField(max_length=50,null=True,blank=True)
    MAC=models.CharField(max_length=50,null=True,blank=True) 
    Category=models.ForeignKey(Category,on_delete=models.SET_NULL,null=True,blank=True)   
    Location=models.ForeignKey(Location,on_delete=models.SET_NULL,null=True,blank=True)  
    Description=models.TextField(null=True,blank=True)
   
    def __str__ (self):
        return self.Name
class Schedule(models.Model):
    
    Process_ID=models.CharField(primary_key=True,max_length=100)  
    Schedule=models.DateTimeField()
    Flag=models.BooleanField(default=False)
    Robot=models.ForeignKey(Robot,on_delete=models.SET_NULL,null=True)

    def __str__ (self):
        return str(self.Process_ID)
        
class History(models.Model):
    Process_ID=models.ForeignKey(Schedule,on_delete=models.SET_NULL,null=True) 
    Robot=models.ForeignKey(Robot,on_delete=models.SET_NULL,null=True)
    Start=models.DateTimeField(null=True,blank=True)
    Stop=models.DateTimeField(null=True,blank=True)
    Forward=models.DateTimeField(null=True,blank=True)
    Backward=models.DateTimeField(null=True,blank=True)
    Backward_Error=models.DateTimeField(null=True,blank=True)
    Status=models.CharField(max_length=50,choices=STATUS_CHOICES)

    def __str__ (self):
        return str(self.Process_ID)




        

project/robots/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from robots.auth_helper import get_sign_in_url, get_token_from_code, store_token, store_user, remove_user_and_token, get_token
from robots.graph_helper import get_user, get_calendar_events
import dateutil.parser



from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.shortcuts import render
from django.contrib.auth.models import User
from robots.models import Robot
from robots.models import Category
from robots.models import Location
from django.db import connection
from .models import Schedule
from .models import History

def home(request):
      context = initialize_context(request)
      return render(request, 'robot/home.html', context)
# </HomeViewSnippet>

# <InitializeContextSnippet>
def initialize_context(request):
  context = {}

  # Check for any errors in the session
  error = request.session.pop('flash_error', None)

  if error != None:
    context['errors'] = []
    context['errors'].append(error)

  # Check for user in the session
  context['user'] = request.session.get('user', {'is_authenticated': False})
  return context
# </InitializeContextSnippet>

# <SignInViewSnippet>
def sign_in(request):
  # Get the sign-in URL
  sign_in_url, state = get_sign_in_url()
  # Save the expected state so we can validate in the callback
  request.session['auth_state'] = state
  # Redirect to the Azure sign-in page
  print(sign_in_url)
  return HttpResponseRedirect(sign_in_url)
# </SignInViewSnippet>

# <SignOutViewSnippet>
def sign_out(request):
  # Clear out the user and token
  remove_user_and_token(request)

  return HttpResponseRedirect(reverse('robots:signin'))
# </SignOutViewSnippet>

# <CallbackViewSnippet>
def callback(request):
  # Get the state saved in session
  print('HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH')
  expected_state = request.session.pop('auth_state', '')
  print(expected_state)
  # Make the token request
  token = get_token_from_code(request.get_full_path(), expected_state)
  
  # Get the user's profile
  user = get_user(token)
  print(user)
  # Save token and user
  store_token(request, token)
  store_user(request, user)

  return HttpResponseRedirect(reverse('robots:home'))
# </CallbackViewSnippet>

# <CalendarViewSnippet>
def calendar(request):
  context = initialize_context(request)

  token = get_token(request)

  events = get_calendar_events(token)

  if events:
    # Convert the ISO 8601 date times to a datetime object
    # This allows the Django template to format the value nicely
    for event in events['value']:
      event['start']['dateTime'] = dateutil.parser.parse(event['start']['dateTime'])
      event['end']['dateTime'] = dateutil.parser.parse(event['end']['dateTime'])

    context['events'] = events['value']

  return render(request, 'robots/calendar.html', context)
# </CalendarViewSnippet>





# Create your views here.
def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def Robot_Listing(request):
    with connection.cursor() as cursor:
      cursor.execute("SELECT * FROM robots_robot" )
      Robot_list = dictfetchall(cursor)

      cursor.execute("SELECT * FROM robots_Category")
      Category_list = dictfetchall(cursor)

      cursor.execute("SELECT * FROM robots_Location")
      Location_list = dictfetchall(cursor)
      context = initialize_context(request)
    return render(request,'robot/home.html',{'context':context,'Robot_list':Robot_list,'Category_list':Category_list,'Location_list':Location_list})

def Robot_List(request):
    with connection.cursor() as cursor:
      cursor.execute("SELECT * FROM robots_robot" )
      Robot_list = dictfetchall(cursor)

      cursor.execute("SELECT * FROM robots_Category")
      Category_list = dictfetchall(cursor)

      cursor.execute("SELECT * FROM robots_Location")
      Location_list = dictfetchall(cursor)
    return render(request,'robot/robot_list.html',{'Robot_list':Robot_list,'Category_list':Category_list,'Location_list':Location_list})

def Location_List(request):
    with connection.cursor() as cursor: 

      cursor.execute("SELECT * FROM robots_Location")
      Location_list = dictfetchall(cursor)
    return render(request,'robot/location_list.html',{'Location_list':Location_list})

def Category_List(request):
    with connection.cursor() as cursor: 

      cursor.execute("SELECT * FROM robots_Category")
      category_list = dictfetchall(cursor)
    return render(request,'robot/category_list.html',{'category_list':category_list})

def Schedule_List(request):
      schedule_list=Schedule.objects.all().order_by('-Schedule')

      return render(request,'robot/schedule_list.html',{'schedule_list':schedule_list})
def Robot_Details(request,id):
      robot_details = Robot.objects.get(id=id)
      category=Category.objects.get(id=robot_details.Category_id)
      location=Location.objects.get(id=robot_details.Location_id)
      return render(request,'robot/robot_details.html',{'robot_details':robot_details,'category':category,'location':location})

def Schedule_Details(request):
      with connection.cursor() as cursor: 
        cursor.execute("SELECT * FROM robots_Location")
        location=dictfetchall(cursor)
        cursor.execute("SELECT * FROM robots_Category")
        category = dictfetchall(cursor)  
        return render(request,'robot/schedule_details.html',{'category':category,'location':location})


def schedule_Submit(request):
     
      if request.method=="POST":
            if request.POST.get('Schedule') and request.POST.get('ProcessId') :                
                 
                  d=Schedule(Process_ID=request.POST.get('ProcessId'),Schedule=request.POST.get('Schedule'),Flag=False,Robot_id=request.POST.get('id'))
                  d.save()
                  with connection.cursor() as cursor:
                        cursor.execute("SELECT * FROM robots_schedule")
                        schedule_list = dictfetchall(cursor)
                        return render(request,'robot/schedule_list.html',{'schedule_list':schedule_list})
            else:
              return render(request,'robot/schedule_details.html')
      else:
        return render(request,'robot/schedule_details.html')



def Robot_Search(request):
     
      if request.method=="POST":
            if request.POST.get('RobotName') :
                  robot_name=request.POST.get('RobotName')
                  robot_details = Robot.objects.get(Name=robot_name)                  
                  robot_id=robot_details.id
                  categoryName=Category.objects.get(id=robot_details.Category_id)
                  locationName=Location.objects.get(id=robot_details.Location_id)               
                  return render(request,'robot/schedule_details.html',{'robot_details':robot_details,'categoryName':categoryName,'locationName':locationName})
            pass
      else:
        return render(request,'robot/schedule_details.html',{'robot_details':robot_details})
def Robot_Listing_Search(request):
     
      if request.method=="POST":
            if request.POST.get('RobotName') :
                  robot_name=request.POST.get('RobotName')
                  robot_details = Robot.objects.get(Name=robot_name) 
                                 
                  robot_id=robot_details.id
                  categoryName=Category.objects.get(id=robot_details.Category_id)
                  locationName=Location.objects.get(id=robot_details.Location_id)
                  with connection.cursor() as cursor:
                        cursor.execute("SELECT * FROM robots_robot where Name='"+robot_name+"'" )
                        Robot_list = dictfetchall(cursor)               
                  return render(request,'robot/robot_list.html',{'Robot_list':Robot_list})
            pass
      else:
        return render(request,'robot/robot_list.html')
def History_List(request):
    with connection.cursor() as cursor:
      cursor.execute("select  [Start],[Stop],[Forward],[Backward],[Backward_Error],[Status],[Process_ID_id],[Robot_id], (select name from robots_robot where id= robot_id)from robots_history" )
      history_list = dictfetchall(cursor)

      cursor.execute("SELECT * FROM robots_Category")
      Category_list = dictfetchall(cursor)

      cursor.execute("SELECT * FROM robots_Location")
      Location_list = dictfetchall(cursor)
    return render(request,'robot/history_list.html',{'history_list':history_list,'Category_list':Category_list,'Location_list':Location_list})

def History_Listing_Search(request):
     
      if request.method=="POST":
            if request.POST.get('ProcessId') :
                  process_id=request.POST.get('ProcessId')                  
                  if History.objects.filter(Process_ID_id=process_id).exists():                        
                        robot_id= (History.objects.get(Process_ID=process_id)).Robot_id
                        robot_name=Robot.objects.get(id=robot_id) 
                        with connection.cursor() as cursor:
                          cursor.execute("select  [Start],[Stop],[Forward],[Backward],[Backward_Error],[Status],[Process_ID_id],Robot_id, (select name from robots_robot where id= robot_id)from robots_history where Process_ID_id='"+process_id+"'" )
                          history_list = dictfetchall(cursor)                                  
                  else:
                        return render(request,'robot/history_list.html')
                                            
                  return render(request,'robot/history_list.html',{'history_list':history_list,'robot_name':robot_name})
            pass
      else:
        return render(request,'robot/history_list.html')

project/robots/templates/robot/history_list.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<body>
     <!-- bradcam_area  -->
     <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>History Listing</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->
<!-- job_listing_area_start  -->
<div class="job_listing_area plus_padding">
    <div class="container">
        <div class="row">
            
            <div class="col-lg-3">
                <form method="POST" action="{%url 'robots:history_listing_search'%}">
                    {% csrf_token %}
                <div class="job_filter white-bg">
                    <div class="form_inner white-bg">
                        <h3>Filter</h3>
                        <form action="#">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="single_field">
                                        <input name="ProcessId" type="text" placeholder="Process ID">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="single_field">
                                        <select class="wide" >
                                            <option data-display="Location">Location</option>
                                            {% for l in Location_list %}                         
                                            <option value="">{{l.Name}}</option>
                                            {% endfor %}
                                          </select>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="single_field">
                                        <select class="wide">
                                            <option data-display="Category">Category</option>
                                            {% for c in Category_list %}                         
                                            <option value="">{{c.Name}}</option>
                                            {% endfor %}
                                          </select>
                                    </div>
                                </div>
                            
                            </div>
                        </form>
                    </div>
               
                    <div class="reset_btn">
                        <button  class="boxed-btn3 w-100" type="submit">Search</button>
                    </div>
                </div> </form>
            </div>
           
            <div class="col-lg-9">
                <div class="recent_joblist_wrap">
                    <div class="recent_joblist white-bg ">
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <h4>Process Listing</h4>
                            </div>
                         
                        </div>
                    </div>
                </div>

                <div class="job_lists m-0">
                    <div class="row">
                        {% for r in history_list %}
                        <div class="col-lg-12 col-md-12">
                           <div class="single_jobs white-bg d-flex justify-content-between">
                               <div class="jobs_left d-flex align-items-center">
                                   
                                   
                                   
                                  <!--  {%url 'robots:robot_details' r.Robot_id %} -->
                                   <div class="jobs_conetent">
                                       <a href="{%url 'robots:history_details' r.Process_ID_id %}"><h4>{{r.Process_ID_id}}</h4></a>
                                       <div class="links_locat d-flex align-items-left">
                                           <div class="location">
                                             <p>Start:     </p><p style="color:rgb(16, 26, 167);"> {{r.Forward}}</p>
                                           </div>
                                           <div class="location">
                                               <p>Stop: </p><p style="color: blue;"> {{r.Forward}}</p>
                                           </div>
                                           <div class="location">
                                               <p>Status :</p><p style="color: blue;"> {{r.Status}}</p>
                                           </div>
                                           <div class="location">
                                            <p>Type :</p><p style="color: blue;"> Robot</p>
                                            </div>
                                         
                                         
                                          <!--  <div class="location">
                                               <p> </i>MAC : {{r.MAC}}</p>
                                           </div> -->
                                       </div>
                                   </div>
                                   
                               </div>
                               <div class="jobs_right">
                                <div class="apply_now">                                   
                                    <a href="{%url 'robots:history_details' r.Process_ID_id %}"  class="boxed-btn3" style="padding-left: 7px;padding-right: 7px;padding-top: 0px;padding-bottom: 0px; font-size: small;">Detials</a>
                                </div>
                               
                               </div>
                             
                           </div>
                           
                        </div>
                        
                       {% endfor %}
                       

                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="pagination_wrap">
                                <ul>
                                    <li><a href="#"> <i class="ti-angle-left"></i> </a></li>
                                    <li><a href="#"><span>01</span></a></li>
                                    <li><a href="#"><span>02</span></a></li>
                                    <li><a href="#"> <i class="ti-angle-right"></i> </a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- job_listing_area_end  -->
</body>
{% endblock body %}
</html>

project/robots/templates/robot/home.html
{% extends 'base.html' %}
{% load static %}
{% block body %}



<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->

    <!-- header-end -->

    <!-- slider_area_start -->
    <div class="slider_area ">
        <div class=" single_slider  d-flex align-items-center slider_bg_1 ">
            <div class="container ">
                <div class="row align-items-center">
                    <div class="col-lg-7 col-md-6">
                        <div class="slider_text ">
                            <h5 class="wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".2s">600+ Robots listed</h5>
                            <h3 class="wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".3s">Improved
                                Production level
                                with LUCA Robotics</h3>
                            <p class="wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".4s">EVERYONE WANTS THE INNOVATION THROUGH ROBOTICS</p>
                           <!--  <div class="sldier_btn wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".5s">
                                <a href="#" class="boxed-btn3">Upload your Resume</a>
                            </div> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="ilstration_img wow fadeInRight d-none d-lg-block text-right" data-wow-duration="1s" data-wow-delay=".2s">
            <img  src="{% static 'static_file/img/banner/banner-img.png'%}" alt="">
        </div>
    </div>
    <!-- slider_area_end -->

    <!-- catagory_area -->
    <div class="catagory_area">
        <div class="container">
            <div class="row cat_search">
                <div class="col-lg-3 col-md-4">
                    <div class="single_input">
                        <input type="text" placeholder="Search keyword">
                    </div>
                </div>
                <div class="col-lg-3 col-md-4">
                    <div class="single_input">
                        <select class="wide" >
                            <option data-display="Location">Location</option>
                            {% for l in Location_list %}                         
                            <option value="">{{l.Name}}</option>
                            {% endfor %}
                          </select>
                    </div>
                </div>
                <div class="col-lg-3 col-md-4">
                    <div class="single_input">
                        <select class="wide">
                            <option data-display="Category">Category</option>
                            {% for c in Category_list %}                         
                            <option value="">{{c.Name}}</option>
                            {% endfor %}
                          </select>
                    </div>
                </div>
                <div class="col-lg-3 col-md-12">
                    <div class="job_btn">
                        <a href="#" class="boxed-btn3">Find Robot</a>
                    </div>
                </div>
            </div>
         
        </div>
    </div>
    <!--/ catagory_area -->

    <!-- popular_catagory_area_start  -->
    <div class="popular_catagory_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="section_title mb-40">
                        <h3>Popolar Categories</h3>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="brouse_job text-right">
                        <a href="{%url 'robots:category_list'%}" class="boxed-btn4">Browse More Category</a>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for c in Category_list %}
                <div class="col-lg-4 col-xl-3 col-md-6">
                    <div class="single_catagory">
                        <a href=""><h4>{{c.Name}}</h4></a>
                        <p> <span>50</span> Available Robot</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- popular_catagory_area_end  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <div class="section_title">
                        <h3>Robot Listing</h3>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="brouse_job text-right">
                        <a href="{%url 'robots:robot_list'%}" class="boxed-btn4">Browse More Robot</a>
                    </div>
                </div>
            </div>
            <div class="job_lists">
                <div class="row">
                    {% for r in Robot_list %}
                     <div class="col-lg-12 col-md-12">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img style="width:49px;height: 49px;" src="{% static 'static_file/img/CR2.JPG'%}" alt="">
                                </div>
                                <div class="jobs_conetent">
                                    <a href="{%url 'robots:robot_details' r.id %}"><h4>{{r.Name}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                          <p>Model: {{r.Model}}</p>
                                        </div>
                                        <div class="location">
                                            <p>SN: {{r.SN}}</p>
                                        </div>
                                        <div class="location">
                                            <p>Software : {{r.Software}}</p>
                                        </div>
                                      
                                        <div class="location">
                                            <p> </i>MAC : {{r.MAC}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">                                   
                                    <a href="{%url 'robots:robot_details' r.id %}" class="boxed-btn3">Schedule</a>
                                </div>
                               
                            </div>
                        </div>
                     </div>
                    {% endfor %}
                 
                    
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->

    <!-- featured_candidates_area_start  -->
    <div class="featured_candidates_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="section_title mb-40">
                        <h3>Popolar Locations</h3>
                    </div>
                    
                </div>
                <div class="col-lg-6">
                    <div class="brouse_job text-right">
                        <a href="{%url 'robots:location_list'%}" class="boxed-btn4">Browse More Location</a>
                    </div>
                </div>
                
            </div>
            <div class="row">
                
                <div class="col-lg-12">
                   
                    <div class="candidate_active owl-carousel">
                        {% for l in Location_list %}
                        <div class="single_candidates text-center">
                           
                            <div class="thumb">
                                <img src="{% static 'static_file/img/candiateds/HQ.JPG'%}" alt="">
                            </div>
                          
                            <a href="#"><h4>{{l.Name}}</h4></a>
                            <p>{{l.Description}}</p>
                        </div>
                        {% endfor %}
                    
                    </div>
                   
                </div>
               
            </div>
            
        </div>
    </div>
    <!-- featured_candidates_area_end  -->

  
    <!-- /testimonial_area  -->


    <!-- footer start -->

    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
  
</body>
 {% endblock body %}
</html>

project/robots/templates/robot/test.html
<h3>hellllllllllllllllllllllllllllllllllllllllo</h3>